<?php
namespace DigitalScout\Models;

class Map extends ApiModel { 
  /**
  * The Digital Scout resource Id
  */
  public $InternalId; /* string */
  /**
  * The partner Id
  */
  public $ExternalId; /* string */
  /**
  * The partner type key (generated by Digital Scout)
  */
  public $ExternalType; /* string */

  public function __construct($data = null) {
    if ($data === null) return;
    
    $this->InternalId = $data["InternalId"];
    $this->ExternalId = $data["ExternalId"];
    $this->ExternalType = $data["ExternalType"];
  }  
}


